In [1]:
import numpy as np

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
a = np.random.rand(10)
print(a)
a[a.argmax()] = 0
print(a)

[0.24290045 0.47577032 0.70386079 0.68310026 0.97815132 0.55313261
 0.24141769 0.50203903 0.92585724 0.18483047]
[0.24290045 0.47577032 0.70386079 0.68310026 0.         0.55313261
 0.24141769 0.50203903 0.92585724 0.18483047]
