## Python

### Блок №1  
Исправьте код ниже, чтобы был такой же вывод, как под комментарием

In [1]:
print("I'm a student and I'll become a \"strong\" programmer")

I'm a student and I'll become a "strong" programmer


In [2]:
print(r"C:\Users\GoodStudent")

C:\Users\GoodStudent


In [3]:
x = "My name is Agent Smith"

In [4]:
print(x[1])

y


In [14]:
print(x[3:17:3])

nesgt



### Блок №2

Запрос ввода осуществляется вызовом функции input(). В функцию можно передать строку, которая будет выведена на экран для общения с пользователем, например:

input('Введите ваш возраст')

Ввод пользователя возвращается функцией input в виде строки и может быть присвоен переменной:

age = input('Введите ваш возраст')

Функция input возвращает строку (даже если пользователь ввёл число). Чтобы сконвертировать строку к целому числу, можно сделать следующее:


In [15]:
age_str = input('Введите ваш возраст') # age_str это строка
age = int(age_str) # age это int

Введите ваш возраст12


Напишите код для следующих 2 задач:

In [ ]:
1. Клиент покупает кофе в кафе. За каждые 6 чашек, 1 чашка даётся в качестве бонуса.
Задача: запросить у пользователя кол-во чашек на покупку, вычислить полагающееся кол-во бонусных чашек кофе и вывести это число через print().

In [26]:
cups_str = input('Введите количество чашек:\n')
cups = int(cups_str)
print (f'Количество бонусных чашек:\n{cups//6}')

Введите количество чашек:
9
Количество бонусных чашек:
1


In [ ]:
2. Запросить у пользователя координаты x и y двух точек на плоскости. Посчитать расстояние между заданными точками и вывести результат.
Примечание: у каждой точки есть две координаты: x и y. Расстояние рассчитывается по формуле, которую вы с лёгкостью найдёте в Интернете.

In [63]:
x_str, y_str = input('Введите координаты x через пробел: '),  input('Введите координаты y через пробел: ') 
x1, y1 = [float(i) for i in x_str.split(' ')]
x2, y2 = [float(i) for i in y_str.split(' ')]
print (f'Расстояние: {((x2-x1)**2 + (y2-y1)**2)**0.5}')

Введите координаты x через пробел: 1 2
Введите координаты y через пробел: 3 4
Расстояние: 2.8284271247461903


In [64]:
print (f'Расстояние: {np.sqrt((x2-x1)**2 + (y2-y1)**2)}')

Расстояние: 2.8284271247461903


In [65]:
from numpy import *

In [66]:
print (f'Расстояние: {sqrt((x2-x1)**2 + (y2-y1)**2)}')

Расстояние: 2.8284271247461903


In [ ]:
from numpy import *

In [ ]:
print (f'Расстояние: {sqrt((x2-x1)**2 + (y2-y1)**2)}')

### Блок №3 (Numpy)

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [47]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [48]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [50]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [52]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [55]:
a = np.array([1, 2, 3, 4])
a[::-1]

array([4, 3, 2, 1])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [64]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [65]:
a = np.array([1,2,0,0,4,0])

In [77]:
np.argwhere(a)

array([[0],
       [1],
       [4]])

Создать 3x3 единичную матрицу

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [82]:
from numpy import random
random.random((3,3,3))

array([[[0.66649016, 0.05602485, 0.02621603],
        [0.837342  , 0.05198873, 0.73730156],
        [0.11419567, 0.14678064, 0.62289781]],

       [[0.68326608, 0.85518004, 0.98843077],
        [0.62972675, 0.45423844, 0.87855453],
        [0.38649953, 0.1244329 , 0.2406743 ]],

       [[0.23060859, 0.60489979, 0.0804553 ],
        [0.22300509, 0.18770648, 0.88974203],
        [0.6846405 , 0.20576492, 0.92298493]]])

Перемножить матрицы 5x3 и 3x2

In [88]:
a = np.ones([5,3])
b = np.ones([3,2])

In [89]:
np.dot(a, b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [16]:
np.set_printoptions(precision = 4, suppress = True)

In [7]:
np.linspace(0, 1, num=12,dtype='float64')[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [121]:
a = np.array([1,2,0,0,6,0])

In [122]:
a[a.argmax()] = 0
a

array([1, 2, 0, 0, 0, 0])

Преобразовать массив из float в int

In [12]:
 a= np.ones(5).astype(int)

Найти наиболее частое значение в массиве

In [13]:
counts = np.bincount(a).arg
print(np.argmax(counts))

1


Найти n наибольших значений в массиве

In [8]:
a = np.array(range(10))
n = 3
a.argsort()[-n:]

array([7, 8, 9])

### Блок №4 (Pandas)

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts). Скачать датасет на свой компьютер и распаковать. Считать csv файл в датафрейм food:

In [27]:
import pandas as pd

In [28]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
pd.set_option('precision', 2)

#food = pd.read_csv('archive.zip',sep='\t')

Посмотреть первые 5 записей

In [30]:
food['code']

0                  3087
1                  4530
2                  4559
3                 16087
4                 16094
              ...      
356022         99567453
356023    9970229501521
356024    9977471758307
356025    9980282863788
356026     999990026839
Name: code, Length: 356027, dtype: object

Сколько наблюдений в наборе данных?


In [144]:
food.shape

(356027, 163)

Сколько столбцов в наборе данных?

In [0]:
food.shape

Напечатайте все названия столбцов

In [151]:
np.set_printoptions(threshold=np.inf)

In [153]:
np.array(food.columns)

array(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity', 'packaging', 'packaging_tags',
       'brands', 'brands_tags', 'categories', 'categories_tags',
       'categories_en', 'origins', 'origins_tags', 'manufacturing_places',
       'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en',
       'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo',
       'cities', 'cities_tags', 'purchase_places', 'stores', 'countries',
       'countries_tags', 'countries_en', 'ingredients_text', 'allergens',
       'allergens_en', 'traces', 'traces_tags', 'traces_en',
       'serving_size', 'no_nutriments', 'additives_n', 'additives',
       'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n',
       'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags',
       'ingredients_that_may_be_from_palm_oil_n',
       'ingredients_that_may_be_from_palm_oil',
   

Какое название у 105 столбца?

In [147]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [148]:
type(food.columns[104])

str

Каково значение имени продукта в 19-м наблюдении?

In [156]:
food.iloc[18]['product_name']

'Lotus Organic Brown Jasmine Rice'

### Блок №5 (Pandas - фильтрация данных)

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep = '\t' )

In [37]:
df.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [175]:
df.shape

(4622, 6)

Как много продуктов стоят более чем $10.00?

In [73]:
def split(x):
    return float(x.split('$')[1])

In [69]:
x='$123'
x.replace('$','')


'123'

In [38]:
df['price']=[split(i) for i in df.item_price]


In [74]:
df['price'] = df.item_price.apply(split)

In [171]:
df['price']=df.item_price.apply(lambda x: float(x.split('$')[1]))

In [172]:
df.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  price  
0                                                NaN     $2.39    2.39  
1                                       [Clementine]     $3.39    3.39  
2                                            [Apple]     $3.39    3.39  
3                                                NaN     $2.39    2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   16.98

In [40]:
df[df.price>10].shape

(1130, 6)

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [176]:
df[['item_name','item_price']].drop_duplicates()

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
...                                     ...        ...
4237                    Chips and Guacamole     $8.50 
4354                       Steak Soft Tacos    $18.50 
4489                    Chips and Guacamole    $17.80 
4509                                  Chips     $1.99 
4510                          Barbacoa Bowl    $11.49 

[209 rows x 2 columns]

Сколько было заказано самого дорогого предмета?

In [41]:
a = df[['item_name','price']].drop_duplicates()
a.sort_values(by = 'price', ascending = False).iloc[0]['item_name']

'Chips and Fresh Tomato Salsa'

In [46]:
product = a.sort_values(by = 'price', ascending = False).iloc[0]['item_name']

In [50]:
df[df.item_name == product]['quantity'].count()

110

In [52]:
df[df.item_name == product]['quantity'].sum()

130

In [51]:
df[df.item_name == product]

order_id  quantity                     item_name choice_description  \
0            1         1  Chips and Fresh Tomato Salsa                NaN   
25          13         1  Chips and Fresh Tomato Salsa                NaN   
55          25         1  Chips and Fresh Tomato Salsa                NaN   
89          39         1  Chips and Fresh Tomato Salsa                NaN   
183         82         1  Chips and Fresh Tomato Salsa                NaN   
...        ...       ...                           ...                ...   
4231      1689         1  Chips and Fresh Tomato Salsa                NaN   
4318      1722         1  Chips and Fresh Tomato Salsa                NaN   
4324      1725         1  Chips and Fresh Tomato Salsa                NaN   
4425      1764         1  Chips and Fresh Tomato Salsa                NaN   
4503      1790         1  Chips and Fresh Tomato Salsa                NaN   

     item_price  price  
0        $2.39    2.39  
25       $2.39    2.39  
55       $2.39    2.39  
89       $2.95    2.95  
183      $2.95    2.95  
...         ...    ...  
4231     $2.95    2.95  
4318     $2.95    2.95  
4324     $2.95    2.95  
4425     $2.95    2.95  
4503     $2.95    2.95  

[110 rows x 6 columns]

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [56]:
df[df.item_name == 'Veggie Salad Bowl'].count()

order_id              18
quantity              18
item_name             18
choice_description    18
item_price            18
price                 18
dtype: int64

In [57]:
df[df.item_name == 'Veggie Salad Bowl'].sum()

order_id                                                          17303
quantity                                                             18
item_name             Veggie Salad BowlVeggie Salad BowlVeggie Salad...
choice_description    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...
item_price            $11.25 $11.25 $11.25 $11.25 $8.75 $8.75 $11.25...
price                                                           1.8e+02
dtype: object

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [62]:
df[(df.item_name == 'Canned Soda') & (df.quantity > 1)]['quantity'].sum()

42