In [2]:
import numpy as np

In [4]:
a = np.array([[1,2],[3, 4]])

In [5]:
a 2 2

array([[1, 2],
       [3, 4]])

In [13]:
b = np.array([1,1])

In [14]:
b 

array([1, 1])

In [15]:
a.dot(b)

array([3, 7])

In [16]:
c = np.zeros([2,1])

In [17]:
c

array([[0.],
       [0.]])

In [18]:
a[0]

array([1, 2])

In [19]:
n = 2
m = 2
l = 1

In [38]:
import itertools

In [41]:
def multiply(a, b):
    #вычислить размерость а и б
    #проверка размерности 
    if m = :   
        for i,j in zip(range(n) , itertools.cycle(range(l))):
            c[i]=sum([a[i,k]*b[k] for k in range(m)])
    elif :
        c
    else :
        c
    return(c)

In [44]:
multiply(a, b).astype(int)

array([[3],
       [7]])

In [35]:
for i in range(n):
    for j in range(l):
        c[i]=sum([a[i,k]*b[k] for k in range(m)])


In [ ]:
for i in range(n):
    for j in range(l):
        c[i] = 0
        for k in range(m):
        c[i] += a[i,k]*b[k] 

In [36]:
c

array([[3.],
       [7.]])