In [28]:
import numpy as np
import pandas as pd
import random
import itertools

In [150]:
a = np.zeros([3,3])
flg=True
stategy = random.sample(range(8), 8)
c = 0

for k in stategy:
    
    index = stategy[k]
    i=index//3
    j=index%3
    if flg:        
            a[i,j] =1

            if ((a[i,:].sum() == 3) | (a[:,j].sum() == 3) | (np.trace(a) ==3)):
                print ('First wins')
                print(a)
                break
            print(a)    
            flg=False
            c=c+1
                                    
    else:
        a[i,j] =-1

        if ((a[i,:].sum() == -3) | (a[:,j].sum() == -3) | (np.trace(a) ==-3)):
                print ('Second wins')
                print(a)
                break
        print(a)    
        flg=True
        c=c+1
      
    if c==8:
        print(a)
        print ('Its a draw')


[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]
[[-1.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]]
[[-1.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  1.  0.]]
[[-1.  0.  0.]
 [-1.  0.  0.]
 [ 1.  1.  0.]]
[[-1.  0.  0.]
 [-1.  0.  1.]
 [ 1.  1.  0.]]
[[-1.  0.  0.]
 [-1. -1.  1.]
 [ 1.  1.  0.]]
[[-1.  1.  0.]
 [-1. -1.  1.]
 [ 1.  1.  0.]]
[[-1.  1. -1.]
 [-1. -1.  1.]
 [ 1.  1.  0.]]
[[-1.  1. -1.]
 [-1. -1.  1.]
 [ 1.  1.  0.]]
Its a draw
